spring:
  application:
    name: SpringLab2
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://junction.proxy.rlwy.net:43795/railway
    username: postgres
    password: GgGNOxbBgBmrtFxcdWZSgEemMoTmBkGO
    driverClassName: org.postgresql.Driver
